version: '3.9'
services:
  metabase:
    image: metabase/metabase-enterprise:v1.46.1
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    - $PWD/database/sample_data.db:/app/metabase.db
    ports:
      - 3001:3000
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - metanet1
  setup:
    image: bash:5.1.16
    container_name: setup
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      metabase:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m
networks:
  metanet1:
    driver: bridge